# Generated by Django 3.2.9 on 2022-02-11 02:07

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=32)),
                ('price_per_kg', models.FloatField(max_length=10)),
                ('season', models.CharField(max_length=32)),
                ('storage_kg', models.FloatField(max_length=32)),
                ('description', models.TextField(max_length=150)),
                ('product_image', imagekit.models.fields.ProcessedImageField(upload_to='Product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=2)),
            ],
        ),
    ]
