# Generated by Django 3.2.9 on 2022-02-11 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.season'),
        ),
    ]
