# Generated by Django 3.2.8 on 2021-11-09 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('product', models.CharField(max_length=32)),
                ('time_created', models.DateField(default=datetime.date.today, verbose_name='Date ')),
            ],
        ),
    ]
