# Generated by Django 3.2.8 on 2021-11-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='number',
            field=models.CharField(default=1, max_length=32),
        ),
    ]
