# Generated by Django 3.2.8 on 2021-11-12 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_shoppingcart_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='time_created',
            field=models.DateField(default=datetime.datetime(2021, 11, 12, 11, 4, 46, 440554), verbose_name='Date '),
        ),
    ]
