# Generated by Django 3.2.8 on 2021-11-12 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_shoppingcart_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2021, 11, 12, 11, 8, 2, 810507), verbose_name='Date '),
        ),
    ]
