# Generated by Django 3.2.8 on 2021-11-12 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_shoppingcart_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 11, 9, 7, 607424), verbose_name='Date '),
        ),
    ]
