# Generated by Django 3.2.8 on 2021-11-15 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_shoppingcart_time_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('product', models.CharField(max_length=32)),
                ('number', models.CharField(default=1, max_length=32)),
                ('time_created', models.DateTimeField(default=datetime.datetime(2021, 11, 15, 14, 18, 18, 637095), verbose_name='Date ')),
            ],
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 14, 18, 18, 637095), verbose_name='Date '),
        ),
    ]
