# Generated by Django 3.2.8 on 2021-11-16 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20211116_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 9, 22, 5, 391719), verbose_name='Date '),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='product',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 9, 22, 5, 391719), verbose_name='Date '),
        ),
    ]
