# Generated by Django 3.2.8 on 2021-11-16 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20211116_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_approved',
            new_name='isApproved',
        ),
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 9, 23, 34, 745023), verbose_name='Date '),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 9, 23, 34, 745023), verbose_name='Date '),
        ),
    ]
