# Generated by Django 3.2.8 on 2021-11-23 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20211116_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='未輸入(不受理無地址訂單，請刪除此訂單並重新寄送)', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 8, 54, 8, 392708), verbose_name='Date '),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 8, 54, 8, 392708), verbose_name='Date '),
        ),
    ]
