# Generated by Django 3.2.8 on 2021-11-23 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20211123_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.CharField(default='2021-11-23 23:54:32.323179', max_length=32),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 23, 54, 32, 323179), verbose_name='Date '),
        ),
    ]
