# Generated by Django 3.2.8 on 2021-11-23 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20211123_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isApproved',
            field=models.CharField(default='否', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.CharField(default='2021-11-24 00:05:26.818566', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 0, 5, 26, 818566), verbose_name='Date '),
        ),
    ]
