# Generated by Django 3.2.8 on 2021-11-23 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20211124_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.CharField(default='2021-11-24 00:11:17.919063', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 0, 11, 17, 919063), verbose_name='Date '),
        ),
    ]
