# Generated by Django 3.2.9 on 2021-12-21 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20211221_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='time_created',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='last_modified',
            field=models.CharField(default=datetime.datetime(2021, 12, 21, 16, 56, 53, 340414), max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.CharField(default='2021-12-21 16:56:53.340414', max_length=20),
        ),
    ]
