# Generated by Django 3.2.9 on 2021-12-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20211221_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.CharField(default='2021-12-21 23:55:06.340441', max_length=32),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='last_modified',
            field=models.CharField(default='2021-12-21 23:55:06', max_length=32),
        ),
    ]
