# Generated by Django 3.2.9 on 2022-02-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20211222_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.CharField(default='伺服器時間: 2022-02-11 09:51:58.859523', max_length=32),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='last_modified',
            field=models.CharField(default='2022-02-11 09:51:58', max_length=32),
        ),
    ]
