# Generated by Django 3.2.9 on 2022-02-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20220211_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.CharField(default='伺服器時間: 2022-02-11 10:01:10.542695', max_length=32),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='last_modified',
            field=models.CharField(default='2022-02-11 10:01:10', max_length=32),
        ),
    ]
