# Generated by Django 3.2.9 on 2022-02-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_auto_20220211_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.CharField(default='伺服器時間: 2022-02-11 10:08:39.741118', max_length=32),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='last_modified',
            field=models.CharField(default='2022-02-11 10:08:39', max_length=32),
        ),
    ]
