# Generated by Django 3.2.9 on 2022-02-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_auto_20220211_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Id_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_id', models.IntegerField(default=0, max_length=32)),
                ('lastes_id', models.IntegerField(default=0, max_length=32)),
                ('name', models.CharField(default=0, max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.CharField(default='伺服器時間: 2022-02-18 23:36:28.418525', max_length=32),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='last_modified',
            field=models.CharField(default='2022-02-18 23:36:28', max_length=32),
        ),
    ]
