# Generated by Django 3.2.9 on 2022-02-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_auto_20220218_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastest_id', models.IntegerField(default=0, max_length=32)),
                ('name', models.CharField(default=0, max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='id_test',
            name='lastes_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.CharField(default='伺服器時間: 2022-02-19 00:31:07.651151', max_length=32),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='last_modified',
            field=models.CharField(default='2022-02-19 00:31:07', max_length=32),
        ),
    ]
