# Generated by Django 3.2.9 on 2022-02-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_auto_20220219_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latest_id',
            old_name='lastest_id',
            new_name='latest_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.CharField(default='伺服器時間: 2022-02-19 00:35:59.360845', max_length=32),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='last_modified',
            field=models.CharField(default='2022-02-19 00:35:59', max_length=32),
        ),
    ]
