# Generated by Django 3.2.9 on 2022-02-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_auto_20220219_0036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Id_test',
        ),
        migrations.DeleteModel(
            name='Latest_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.CharField(default='伺服器時間: 2022-02-22 21:25:42.940019', max_length=32),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='last_modified',
            field=models.CharField(default='2022-02-22 21:25:42', max_length=32),
        ),
    ]
